/-
Copyright (c) 2026 Sanghyeok Park. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sanghyeok Park
-/
module

public import Mathlib.RingTheory.MvPolynomial.BuchbergerCriterion
public import Mathlib.RingTheory.Noetherian.Defs
public import Mathlib.RingTheory.Polynomial.Basic

/-!
# An abstract Buchberger procedure

This file starts the formalization of Becker--Weispfenning--Kredel,
Theorem 5.53.

The procedure is represented by an abstract step relation on sets of
polynomials: choose a pair from the current set, reduce its S-polynomial to
a nonzero normal form with unit leading coefficient, and add that normal
form to the set.

The correctness theorem in this file says that any set reached by such steps
that satisfies the S-polynomial condition is a Gröbner basis of the ideal
generated by the initial set. Over a Noetherian polynomial ring, every state
reaches a terminal state. Over a field with finitely many variables, finite
initial sets reach finite terminal sets.
-/

@[expose] public section

namespace MonomialOrder

open MvPolynomial
open scoped MonomialOrder Reduction

variable {σ : Type*} (m : MonomialOrder σ)

section CommRing

variable {R : Type*} [CommRing R]

/-- The ideal generated by the leading terms of the elements of `G`. -/
noncomputable def leadingTermIdeal (G : Set (MvPolynomial σ R)) : Ideal (MvPolynomial σ R) :=
  Ideal.span (m.leadingTerm '' G)

/--
One abstract Buchberger step.

The next set is obtained by adjoining a nonzero normal form of an
S-polynomial of two current generators. The unit leading coefficient
assumption is included so that the existing reduction API over general
coefficient rings remains available after adjoining the new polynomial.
-/
def BuchbergerStep
    (G H : Set (MvPolynomial σ R)) : Prop :=
  ∃ p ∈ G, ∃ q ∈ G, ∃ h : MvPolynomial σ R,
    Relation.IsNormalFormOf (m.ReducesToSet G) (m.sPolynomial p q) h ∧
      h ≠ 0 ∧
        IsUnit (m.leadingCoeff h) ∧
          H = insert h G

/--
The S-polynomial condition: every S-polynomial of two elements reduces to zero
modulo the set.
-/
def SPolynomialCondition (G : Set (MvPolynomial σ R)) : Prop :=
  ∀ p ∈ G, ∀ q ∈ G, m.sPolynomial p q ⟶*[m, G] 0

namespace BuchbergerStep

theorem span_eq
    {G H : Set (MvPolynomial σ R)}
    (hstep : m.BuchbergerStep G H) :
    Ideal.span H = Ideal.span G := by
  rcases hstep with ⟨p, hpG, q, hqG, h, hnf, _hh, _hunit, rfl⟩
  have hsp_mem :
      m.sPolynomial p q ∈ Ideal.span G :=
    m.sPolynomial_mem_ideal
      (Ideal.subset_span hpG)
      (Ideal.subset_span hqG)
  have hsub :
      m.sPolynomial p q - h ∈ Ideal.span G :=
    m.sub_mem_span_of_reflTransGen G hnf.1
  have hh_mem : h ∈ Ideal.span G := by
    have htmp :
        m.sPolynomial p q - (m.sPolynomial p q - h) ∈ Ideal.span G :=
      Ideal.sub_mem (Ideal.span G) hsp_mem hsub
    have hEq : m.sPolynomial p q - (m.sPolynomial p q - h) = h := by
      ring
    simpa [hEq] using htmp
  apply le_antisymm
  · refine Ideal.span_le.mpr ?_
    intro f hf
    rcases Set.mem_insert_iff.mp hf with rfl | hfG
    · exact hh_mem
    · exact Ideal.subset_span hfG
  · exact Ideal.span_mono (Set.subset_insert h G)

/-- One abstract Buchberger step preserves finiteness of the polynomial set. -/
theorem finite
    {G H : Set (MvPolynomial σ R)}
    (hstep : m.BuchbergerStep G H)
    (hG : G.Finite) :
    H.Finite := by
  rcases hstep with ⟨_, _, _, _, h, _, _, _, rfl⟩
  exact hG.insert h

theorem leadingCoeff_condition
    {G H : Set (MvPolynomial σ R)}
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0)
    (hstep : m.BuchbergerStep G H) :
    ∀ h ∈ H, IsUnit (m.leadingCoeff h) ∨ h = 0 := by
  rcases hstep with ⟨p, hpG, q, hqG, h, hnf, hh, hunit, rfl⟩
  intro f hf
  rcases Set.mem_insert_iff.mp hf with rfl | hfG
  · exact Or.inl hunit
  · exact hG₀ f hfG

theorem not_leadingTerm_mem_leadingTermIdeal_of_isNormalForm
    (G : Set (MvPolynomial σ R))
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0)
    {h : MvPolynomial σ R}
    (hh : h ≠ 0)
    (hnf : Relation.IsNormalForm (m.ReducesToSet G) h) :
    m.leadingTerm h ∉ m.leadingTermIdeal G := by
  classical
  intro hLT_mem
  have hLT_mem_monic :
      m.leadingTerm h ∈
        Ideal.span
          ((fun p : MvPolynomial σ R =>
              MvPolynomial.monomial (m.degree p) (1 : R)) ''
            (G \ {0})) := by
    simpa [MonomialOrder.leadingTermIdeal,
      MonomialOrder.span_leadingTerm_eq_span_monomial₀
        (m := m) (B := G) hG₀] using hLT_mem
  have hLT_mem_exp :
      m.leadingTerm h ∈
        Ideal.span
          ((fun a : σ →₀ ℕ =>
              MvPolynomial.monomial a (1 : R)) ''
            (m.degree '' (G \ {0}))) := by
    simpa [Set.image_image, Function.comp_def] using hLT_mem_monic
  have hmem :=
    (MvPolynomial.mem_ideal_span_monomial_image
      (x := m.leadingTerm h)
      (s := m.degree '' (G \ {0}))).1 hLT_mem_exp
  have hdeg_in_support :
      m.degree h ∈ (m.leadingTerm h).support := by
    rw [MonomialOrder.support_leadingTerm' (m := m) hh]
    simp
  rcases hmem (m.degree h) hdeg_in_support with
    ⟨a, ha, hale⟩
  rcases ha with ⟨p, hpG0, hpa⟩
  rcases hpG0 with ⟨hpG, hp_not_zero_set⟩
  have hp_ne : p ≠ 0 := by
    simpa [Set.mem_singleton_iff] using hp_not_zero_set
  subst a
  rcases le_iff_exists_add.mp hale with ⟨s, hs⟩
  have hs' : s + m.degree p = m.degree h := by
    simpa [add_comm] using hs.symm
  have hp_unit : IsUnit (m.leadingCoeff p) := by
    rcases hG₀ p hpG with hunit | hp0
    · exact hunit
    · exact False.elim (hp_ne hp0)
  rcases hp_unit with ⟨u, hu⟩
  let c : R := ((u⁻¹ : Rˣ) : R) * h.coeff (m.degree h)
  have hc : c * m.leadingCoeff p =
      h.coeff (m.degree h) := by
    unfold c
    rw [← hu]
    calc
      (((u⁻¹ : Rˣ) : R) * h.coeff (m.degree h)) * (u : R)
          = (((u⁻¹ : Rˣ) : R) * (u : R)) *
              h.coeff (m.degree h) := by
            ring
      _ = h.coeff (m.degree h) := by
            simp
  have hred :
      m.ReducesToSet G h (h - monomial s c * p) := by
    exact
      ⟨p, hpG, m.degree h, hp_ne,
        MonomialOrder.degree_mem_support hh,
        s, hs', c, hc, rfl⟩
  exact hnf _ hred

theorem leadingTermIdeal_lt
    {G H : Set (MvPolynomial σ R)}
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0)
    (hstep : m.BuchbergerStep G H) :
    m.leadingTermIdeal G < m.leadingTermIdeal H := by
  rcases hstep with ⟨p, hpG, q, hqG, h, hnf, hh, hunit, rfl⟩
  have hle :
      m.leadingTermIdeal G ≤ m.leadingTermIdeal (insert h G) := by
    unfold MonomialOrder.leadingTermIdeal
    refine Ideal.span_mono ?_
    rintro _ ⟨g, hgG, rfl⟩
    exact ⟨g, by simp [hgG], rfl⟩
  refine lt_iff_le_not_ge.mpr ⟨hle, ?_⟩
  intro hge
  have hLT_mem_insert :
      m.leadingTerm h ∈ m.leadingTermIdeal (insert h G) := by
    exact Ideal.subset_span ⟨h, by simp, rfl⟩
  exact
    not_leadingTerm_mem_leadingTermIdeal_of_isNormalForm
      m G hG₀ hh hnf.2 (hge hLT_mem_insert)

end BuchbergerStep

theorem IsGroebnerBasis.of_sPolynomialCondition
    [NoZeroDivisors R]
    (G : Set (MvPolynomial σ R)) (I : Ideal (MvPolynomial σ R))
    (hspan : Ideal.span G = I)
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0)
    (hcondition : m.SPolynomialCondition G) :
    m.IsGroebnerBasis G I :=
  IsGroebnerBasis.of_sPolynomial_reflTransGen_zero
    m G I hspan hG₀ hcondition

theorem ReflTransGen_BuchbergerStep.span_eq
    {G H : Set (MvPolynomial σ R)}
    (hsteps : Relation.ReflTransGen m.BuchbergerStep G H) :
    Ideal.span H = Ideal.span G := by
  induction hsteps with
  | refl =>
      rfl
  | tail _ hstep ih =>
      exact (BuchbergerStep.span_eq m hstep).trans ih

/-- A finite sequence of abstract Buchberger steps preserves finiteness. -/
theorem ReflTransGen_BuchbergerStep.finite
    {G H : Set (MvPolynomial σ R)}
    (hsteps : Relation.ReflTransGen m.BuchbergerStep G H)
    (hG : G.Finite) :
    H.Finite := by
  induction hsteps with
  | refl =>
      exact hG
  | tail _ hstep ih =>
      exact BuchbergerStep.finite m hstep ih

theorem ReflTransGen_BuchbergerStep.leadingCoeff_condition
    {G H : Set (MvPolynomial σ R)}
    (hsteps : Relation.ReflTransGen m.BuchbergerStep G H)
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0) :
    ∀ h ∈ H, IsUnit (m.leadingCoeff h) ∨ h = 0 := by
  induction hsteps with
  | refl =>
      exact hG₀
  | tail _ hstep ih =>
      exact BuchbergerStep.leadingCoeff_condition m ih hstep

/--
Correctness of the abstract Buchberger procedure.

If `H` is reached from `G` by Buchberger steps and satisfies the S-polynomial
condition, then `H` is a Gröbner basis of the original ideal `I`.
-/
theorem IsGroebnerBasis.of_buchbergerSteps_of_sPolynomialCondition
    [NoZeroDivisors R]
    {G H : Set (MvPolynomial σ R)} {I : Ideal (MvPolynomial σ R)}
    (hsteps : Relation.ReflTransGen m.BuchbergerStep G H)
    (hspan : Ideal.span G = I)
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0)
    (hcondition : m.SPolynomialCondition H) :
    m.IsGroebnerBasis H I := by
  have hHspan : Ideal.span H = I :=
    (ReflTransGen_BuchbergerStep.span_eq m hsteps).trans hspan
  have hH₀ : ∀ h ∈ H, IsUnit (m.leadingCoeff h) ∨ h = 0 :=
    ReflTransGen_BuchbergerStep.leadingCoeff_condition m hsteps hG₀
  exact IsGroebnerBasis.of_sPolynomialCondition m H I hHspan hH₀ hcondition

/--
States for the abstract Buchberger procedure over a general coefficient
ring. The invariant records that every current generator is either zero or
has unit leading coefficient.
-/
def BuchbergerState : Type _ :=
  { G : Set (MvPolynomial σ R) // ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0 }

namespace BuchbergerState

/-- The step relation on Buchberger states. -/
def Step
    (G H : MonomialOrder.BuchbergerState (R := R) m) : Prop :=
  m.BuchbergerStep G.1 H.1

theorem step_leadingTermIdeal_lt
    {G H : MonomialOrder.BuchbergerState (R := R) m}
    (hstep : Step (R := R) (m := m) G H) :
    m.leadingTermIdeal G.1 < m.leadingTermIdeal H.1 :=
  BuchbergerStep.leadingTermIdeal_lt m G.2 hstep

/--
Noetherian termination for the abstract Buchberger step relation.

This is the ACC argument underlying Buchberger's algorithm: every genuine
step strictly increases the leading-term ideal, and this cannot happen
indefinitely in a Noetherian polynomial ring.
-/
theorem wellFounded_flip
    [IsNoetherianRing (MvPolynomial σ R)] :
    WellFounded (flip (Step (R := R) (m := m))) := by
  have hIdealWF :
      WellFounded
        ((· > ·) :
          Ideal (MvPolynomial σ R) → Ideal (MvPolynomial σ R) → Prop) :=
    IsNoetherian.wf
      (R := MvPolynomial σ R)
      (M := MvPolynomial σ R)
      (inferInstance : IsNoetherian (MvPolynomial σ R) (MvPolynomial σ R))
  refine
    (InvImage.wf
      (fun G : MonomialOrder.BuchbergerState (R := R) m =>
        m.leadingTermIdeal G.1)
      hIdealWF).mono ?_
  intro H G hstep
  exact step_leadingTermIdeal_lt (R := R) (m := m) hstep

/-- A terminal state has no outgoing Buchberger step. -/
def Terminal (G : MonomialOrder.BuchbergerState (R := R) m) : Prop :=
  ∀ H : MonomialOrder.BuchbergerState (R := R) m,
    ¬ Step (R := R) (m := m) G H

/-- Every state reaches a terminal state in a Noetherian polynomial ring. -/
theorem exists_terminal
    [IsNoetherianRing (MvPolynomial σ R)]
    (G : MonomialOrder.BuchbergerState (R := R) m) :
    ∃ H : MonomialOrder.BuchbergerState (R := R) m,
      Relation.ReflTransGen (Step (R := R) (m := m)) G H ∧
        Terminal (R := R) (m := m) H := by
  classical
  let P : MonomialOrder.BuchbergerState (R := R) m → Prop :=
    fun G =>
      ∃ H : MonomialOrder.BuchbergerState (R := R) m,
        Relation.ReflTransGen (Step (R := R) (m := m)) G H ∧
          Terminal (R := R) (m := m) H
  change P G
  refine (wellFounded_flip (R := R) (m := m)).induction (C := P) G ?_
  intro G ih
  by_cases hterm : Terminal (R := R) (m := m) G
  · exact ⟨G, Relation.ReflTransGen.refl, hterm⟩
  · simp only [Terminal, not_forall, Classical.not_not] at hterm
    rcases hterm with ⟨H, hGH⟩
    rcases ih H hGH with ⟨K, hHK, hKterm⟩
    exact ⟨K, (Relation.ReflTransGen.single hGH).trans hHK, hKterm⟩

/--
If every nonzero polynomial has unit leading coefficient, then a terminal
Buchberger state satisfies the S-polynomial condition.

This hypothesis is automatic over fields, and it is the point where the
general coefficient-ring version needs a coefficient condition beyond
Noetherianity.
-/
theorem sPolynomialCondition_of_terminal
    (hunit : ∀ f : MvPolynomial σ R, f ≠ 0 → IsUnit (m.leadingCoeff f))
    {G : MonomialOrder.BuchbergerState (R := R) m}
    (hterm : Terminal (R := R) (m := m) G) :
    m.SPolynomialCondition G.1 := by
  intro p hpG q hqG
  rcases
    Relation.exists_normalFormOf_of_wellFounded_flip
      (ReducesToSet.wellFounded m G.1)
      (m.sPolynomial p q)
    with ⟨h, hnf⟩
  by_cases hh : h = 0
  · simpa [hh] using hnf.1
  · exfalso
    let H : MonomialOrder.BuchbergerState (R := R) m :=
      ⟨insert h G.1, by
        intro f hf
        rcases Set.mem_insert_iff.mp hf with hf_eq | hfG
        · subst f
          exact Or.inl (hunit h hh)
        · exact G.2 f hfG⟩
    have hstep : Step (R := R) (m := m) G H := by
      refine ⟨p, hpG, q, hqG, h, hnf, hh, hunit h hh, rfl⟩
    exact hterm H hstep

/--
Existence and correctness of a terminal abstract Buchberger run.

Starting from `G`, the abstract procedure reaches a terminal state `H`; if
nonzero normal forms have unit leading coefficient, then `H` is a Gröbner
basis of the original ideal `I`.
-/
theorem exists_isGroebnerBasis_terminal
    [NoZeroDivisors R]
    [IsNoetherianRing (MvPolynomial σ R)]
    (hunit : ∀ f : MvPolynomial σ R, f ≠ 0 → IsUnit (m.leadingCoeff f))
    {G : Set (MvPolynomial σ R)} {I : Ideal (MvPolynomial σ R)}
    (hspan : Ideal.span G = I)
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0) :
    ∃ H : MonomialOrder.BuchbergerState (R := R) m,
      Relation.ReflTransGen (Step (R := R) (m := m)) ⟨G, hG₀⟩ H ∧
        Terminal (R := R) (m := m) H ∧
          m.IsGroebnerBasis H.1 I := by
  rcases exists_terminal (R := R) (m := m) ⟨G, hG₀⟩ with ⟨H, hsteps, hterm⟩
  have hcondition :
      m.SPolynomialCondition H.1 :=
    sPolynomialCondition_of_terminal (R := R) (m := m) hunit hterm
  have hsteps_sets :
      Relation.ReflTransGen m.BuchbergerStep G
        H.1 := by
    clear hterm hcondition
    change
      Relation.ReflTransGen m.BuchbergerStep
        (⟨G, hG₀⟩ : MonomialOrder.BuchbergerState (R := R) m).1
        H.1
    induction hsteps with
    | refl =>
        exact Relation.ReflTransGen.refl
    | tail _ hstep ih =>
        exact ih.tail hstep
  refine ⟨H, hsteps, hterm, ?_⟩
  exact
    IsGroebnerBasis.of_buchbergerSteps_of_sPolynomialCondition
      m hsteps_sets hspan hG₀ hcondition

section Field

variable {K : Type*} [Field K]

theorem leadingCoeff_isUnit_of_ne_zero
    (f : MvPolynomial σ K) (hf : f ≠ 0) :
    IsUnit (m.leadingCoeff f) :=
  isUnit_iff_ne_zero.mpr (m.leadingCoeff_ne_zero_iff.mpr hf)

theorem leadingCoeff_condition_of_field
    (G : Set (MvPolynomial σ K)) :
    ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0 := by
  intro g _hg
  by_cases hg : g = 0
  · exact Or.inr hg
  · exact Or.inl (leadingCoeff_isUnit_of_ne_zero m g hg)

/--
Field version of the terminal-state correctness theorem.

Over a field, every nonzero leading coefficient is a unit, so the
coefficient condition in `exists_isGroebnerBasis_terminal` is automatic.
-/
theorem exists_isGroebnerBasis_terminal_field
    [IsNoetherianRing (MvPolynomial σ K)]
    {G : Set (MvPolynomial σ K)} {I : Ideal (MvPolynomial σ K)}
    (hspan : Ideal.span G = I) :
    ∃ H : MonomialOrder.BuchbergerState (R := K) m,
      Relation.ReflTransGen (Step (R := K) (m := m))
          ⟨G, leadingCoeff_condition_of_field m G⟩ H ∧
        Terminal (R := K) (m := m) H ∧
          m.IsGroebnerBasis H.1 I :=
  exists_isGroebnerBasis_terminal
    (R := K) (m := m)
    (fun f hf => leadingCoeff_isUnit_of_ne_zero m f hf)
    hspan
    (leadingCoeff_condition_of_field m G)

/--
Finite-variable field version of the abstract Buchberger procedure.

If the coefficient field is Noetherian and the variable type is finite, the
Noetherian hypothesis on `MvPolynomial σ K` is provided by Hilbert's basis
theorem.
-/
theorem exists_isGroebnerBasis_terminal_field_of_finite_variables
    [IsNoetherianRing K] [Finite σ]
    {G : Set (MvPolynomial σ K)} {I : Ideal (MvPolynomial σ K)}
    (hspan : Ideal.span G = I) :
    ∃ H : MonomialOrder.BuchbergerState (R := K) m,
      Relation.ReflTransGen (Step (R := K) (m := m))
          ⟨G, leadingCoeff_condition_of_field m G⟩ H ∧
        Terminal (R := K) (m := m) H ∧
          m.IsGroebnerBasis H.1 I :=
  exists_isGroebnerBasis_terminal_field
    (K := K) (m := m) hspan

/--
Finite-output version of the terminal-state correctness theorem over a field
with finitely many variables.

Starting from a finite polynomial set, the abstract procedure reaches a finite
terminal set that is a Gröbner basis of the ideal generated by the initial set.
-/
theorem exists_finite_isGroebnerBasis_terminal_field_of_finite_variables
    [IsNoetherianRing K] [Finite σ]
    {G : Set (MvPolynomial σ K)} {I : Ideal (MvPolynomial σ K)}
    (hG : G.Finite)
    (hspan : Ideal.span G = I) :
    ∃ H : MonomialOrder.BuchbergerState (R := K) m,
      Relation.ReflTransGen (Step (R := K) (m := m))
          ⟨G, leadingCoeff_condition_of_field m G⟩ H ∧
        Terminal (R := K) (m := m) H ∧
          H.1.Finite ∧
            m.IsGroebnerBasis H.1 I := by
  rcases exists_isGroebnerBasis_terminal_field_of_finite_variables
    (K := K) (m := m) hspan with ⟨H, hsteps, hterm, hGB⟩
  refine ⟨H, hsteps, hterm, ?_, hGB⟩
  clear hterm hGB
  induction hsteps with
  | refl =>
      exact hG
  | tail _ hstep ih =>
      exact BuchbergerStep.finite m hstep ih

end Field

end BuchbergerState

end CommRing

end MonomialOrder
