module

public import Mathlib.Logic.Relation.PolynomialReductions
public import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# Gröbner basis criterion

This file formalizes the Gröbner basis criterion in the setting of
Becker--Weispfenning--Kredel, Theorem 5.35.

We take the leading-term criterion for a subset `G` itself as the definition:

* a set `G` satisfies `IsGroebner` if the ideal generated by the leading
  terms of all elements of `⟨G⟩` is equal to the ideal generated by the
  leading terms of elements of `G`.

Here `⟨G⟩` is written in Lean as `Ideal.span G`.

The file then relates this definition to the reduction-theoretic properties
appearing in Theorem 5.35:

* local confluence of reduction modulo `G`;
* confluence of reduction modulo `G`;
* uniqueness of normal forms;
* the Church--Rosser property;
* reduction to zero for all elements of `⟨G⟩`;
* reducibility of all nonzero elements of `⟨G⟩`;
* uniqueness of normal-form representatives modulo `⟨G⟩`.

The main implication cycle follows the proof of Theorem 5.35:

* `IsGroebner G` implies uniqueness of normal-form representatives modulo
  `⟨G⟩`;
* uniqueness of normal-form representatives implies the Church--Rosser
  property;
* the Church--Rosser property is equivalent to reduction to zero for all
  elements of `⟨G⟩`;
* reduction to zero for all elements of `⟨G⟩` implies reducibility of all
  nonzero elements of `⟨G⟩`;
* reducibility of all nonzero elements of `⟨G⟩` implies `IsGroebner G`.

After this cycle is established, the equivalences with local confluence,
confluence, uniqueness of normal forms, Church--Rosser, reduction to zero,
reducibility, and uniqueness of normal-form representatives are packaged as
separate theorem statements.
-/

@[expose] public section

namespace MonomialOrder

open MvPolynomial
open scoped MonomialOrder Reduction

variable {σ : Type*} (m : MonomialOrder σ)

section CommSemiring

variable {R : Type*} [CommSemiring R]

def IsGroebner
    (G : Set (MvPolynomial σ R)) : Prop :=
  Ideal.span
      (m.leadingTerm ''
        (((Ideal.span G : Ideal (MvPolynomial σ R)) :
          Set (MvPolynomial σ R)))) =
    Ideal.span (m.leadingTerm '' G)

/-- A subset `G` of an ideal `I` is said to be a Gröbner basis if:

1. `G` is contained in `I` (i.e., all polynomials in `G` belong to the ideal `I`).
2. The ideal generated by the leading terms of all polynomials in `I` is equal to
   the ideal generated by the leading terms of the polynomials in `G`.
-/
def IsGroebnerBasis (G : Set (MvPolynomial σ R)) (I : Ideal (MvPolynomial σ R)) : Prop :=
  G ⊆ I ∧ Ideal.span (m.leadingTerm '' ↑I) = Ideal.span (m.leadingTerm '' G)

theorem IsGroebnerBasis.isGroebner
    {G : Set (MvPolynomial σ R)} {I : Ideal (MvPolynomial σ R)}
    (h : m.IsGroebnerBasis G I) :
    m.IsGroebner G := by
  rcases h with ⟨hGI, hLT⟩
  unfold MonomialOrder.IsGroebner
  apply le_antisymm
  · refine Ideal.span_le.mpr ?_
    rintro _ ⟨f, hfspan, rfl⟩
    have hfI : f ∈ I := Ideal.span_le.mpr hGI hfspan
    have hfLT :
        m.leadingTerm f ∈
          Ideal.span (m.leadingTerm '' (I : Set (MvPolynomial σ R))) :=
      Ideal.subset_span ⟨f, hfI, rfl⟩
    simpa [hLT] using hfLT
  · refine Ideal.span_le.mpr ?_
    rintro _ ⟨g, hgG, rfl⟩
    exact Ideal.subset_span ⟨g, Ideal.subset_span hgG, rfl⟩

end CommSemiring

namespace IsGroebner

section CommRing

variable {R : Type*} [CommRing R]
/--
The zero polynomial is in normal form with respect to reduction modulo `G`.
-/
theorem zero_isNormalForm
    (G : Set (MvPolynomial σ R)) :
    Relation.IsNormalForm (m.ReducesToSet G)
      (0 : MvPolynomial σ R) := by
  intro f h
  rcases h with ⟨p, hpG, t, hp_ne, ht, s, hs, c, hc, hf⟩
  simp only [support_zero, Finset.notMem_empty] at ht

/--
Theorem 5.35: item (iv) iff item (v).

The Church--Rosser property is equivalent to the statement that every element
of `⟨G⟩` reduces to zero modulo `G`.
-/
theorem churchRosser_iff_idealElements_reduceTo_zero
    (G : Set (MvPolynomial σ R))
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0) :
    Relation.ChurchRosser (m.ReducesToSet G) ↔
      ∀ f : MvPolynomial σ R,
        f ∈ Ideal.span G →
          f ⟶*[m, G] 0 := by
  constructor
  · intro hcr f hf
    have heqv : f ⟷*[m, G] 0 := by
      apply (m.eqvGen_iff_sub_mem_span G hG₀).2
      simpa using hf
    rcases hcr heqv with ⟨d, hfd, h0d⟩
    have hd0 : d = 0 :=
      Relation.ReflTransGen.eq_of_isNormalForm
        (zero_isNormalForm m G)
        h0d
    simpa [hd0] using hfd
  · intro hred f g heqv
    have hsub : f - g ∈ Ideal.span G :=
      (m.eqvGen_iff_sub_mem_span G hG₀).1 heqv
    have hfg : f - g ⟶*[m, G] 0 :=
      hred (f - g) hsub
    exact m.join_of_sub_reflTransGen_zero G hG₀ f g hfg

/--
Theorem 5.35: item (v) implies item (vi).

If every element of `⟨G⟩` reduces to zero modulo `G`, then every
nonzero element of `⟨G⟩` is reducible modulo `G`.
-/
theorem idealElements_reduceTo_zero_imp_nonzero_idealElements_reducible
    (G : Set (MvPolynomial σ R)) :
    (∀ f : MvPolynomial σ R,
      f ∈ Ideal.span G →
        f ⟶*[m, G] 0) →
      ∀ f : MvPolynomial σ R,
        f ≠ 0 →
        f ∈ Ideal.span G →
          m.ReducibleSet G f := by
  intro hred f hf_ne hfI
  have hfzero : f ⟶*[m, G] 0 :=
    hred f hfI
  rcases Relation.ReflTransGen.cases_head hfzero with hEq | ⟨h, hfh, _hh0⟩
  · exact False.elim (hf_ne hEq)
  · exact ⟨h, hfh⟩

/--
Theorem 5.35: item (vi) implies Gröbner basis definition.
-/
theorem nonzero_idealElements_reducible_imp_isGroebner
    (G : Set (MvPolynomial σ R)) :
    (∀ f : MvPolynomial σ R,
      f ≠ 0 →
      f ∈ Ideal.span G →
        m.ReducibleSet G f) →
      m.IsGroebner G := by
  intro hred
  -- First prove the top-reducibility form of item (vi).
  -- This is the internal `(vi) -> (vii)` step.
  have htop_all :
      ∀ f : MvPolynomial σ R,
        f ≠ 0 →
        f ∈ Ideal.span G →
          ∃ p ∈ G, p ≠ 0 ∧
            ∃ s : σ →₀ ℕ,
              s + m.degree p = m.degree f ∧
                ∃ c : R,
                  c * m.leadingCoeff p = f.coeff (m.degree f) := by
    intro f
    refine
      (ReducesToSet.wellFounded m G).induction
        (C := fun f : MvPolynomial σ R =>
          f ≠ 0 →
          f ∈ Ideal.span G →
            ∃ p ∈ G, p ≠ 0 ∧
              ∃ s : σ →₀ ℕ,
                s + m.degree p = m.degree f ∧
                  ∃ c : R,
                    c * m.leadingCoeff p = f.coeff (m.degree f))
        f
        ?_
    intro f ih hf_ne hfI
    rcases hred f hf_ne hfI with ⟨g, hfg⟩
    have hfg_step : m.ReducesToSet G f g := hfg
    rcases hfg with ⟨p, hpG, t, hp_ne, ht, s, hs, c, hc, hg⟩
    by_cases htop : t = m.degree f
    · rw [htop] at hs hc
      exact ⟨p, hpG, hp_ne, s, hs, c, hc⟩
    · have hsub : f - g ∈ Ideal.span G :=
        m.sub_mem_span_of_reducesToSet G hfg_step
      have hgI : g ∈ Ideal.span G := by
        have htmp : f - (f - g) ∈ Ideal.span G :=
          Ideal.sub_mem (Ideal.span G) hfI hsub
        have hEq : f - (f - g) = g := by
          ring
        simpa [hEq] using htmp
      have hnonTop :
          m.degree g = m.degree f ∧
            g ≠ 0 ∧
              g.coeff (m.degree f) = f.coeff (m.degree f) := by
        let q : MvPolynomial σ R := monomial s c * p
        have ht_le : t ≼[m] m.degree f :=
          m.le_degree ht
        have ht_lt : t ≺[m] m.degree f := by
          have hne_syn : m.toSyn t ≠ m.toSyn (m.degree f) := by
            intro hsyn
            exact htop (m.toSyn.injective hsyn)
          exact lt_of_le_of_ne ht_le hne_syn
        have hmon_le :
            m.degree (monomial s c : MvPolynomial σ R) ≼[m] s := by
          exact degree_monomial_le c
        have hmon_add :
            m.degree (monomial s c : MvPolynomial σ R) + m.degree p
              ≼[m] s + m.degree p := by
          simp only [map_add]
          exact add_le_add_left hmon_le (m.toSyn (m.degree p))
        have hq_le_t : m.degree q ≼[m] t := by
          unfold q
          exact le_trans m.degree_mul_le (by simpa [hs] using hmon_add)
        have hq_lt : m.degree q ≺[m] m.degree f :=
          lt_of_le_of_lt hq_le_t ht_lt
        have hq_lt_prod :
            m.degree (monomial s c * p) ≺[m] m.degree f := by
          simpa [q] using hq_lt
        have hdeg_eq : m.degree g = m.degree f := by
          simpa [hg] using
            (m.degree_sub_of_lt
              (f := f)
              (g := monomial s c * p)
              hq_lt_prod)
        have hcoeff_eq :
            g.coeff (m.degree f) = f.coeff (m.degree f) := by
          rw [hg, coeff_sub]
          have hprod_zero :
              (monomial s c * p).coeff (m.degree f) = 0 := by
            rw [← notMem_support_iff]
            intro hmem
            have hle_prod :
                m.degree f ≼[m] m.degree (monomial s c * p) :=
              m.le_degree hmem
            have hlt_self : m.degree f ≺[m] m.degree f :=
              lt_of_le_of_lt hle_prod hq_lt_prod
            exact (lt_irrefl _ hlt_self)
          simp [hprod_zero]
        have hg_ne : g ≠ 0 := by
          intro hg0
          have hfdeg0 : m.degree f = 0 := by
            simpa [hg0] using hdeg_eq.symm
          have ht_eq_zero : t = 0 := by
            apply m.toSyn.injective
            apply le_antisymm
            · simpa [hfdeg0] using m.le_degree ht
            · have hzero_le_t : (0 : σ →₀ ℕ) ≤ t := by
                change ∀ a, (0 : σ →₀ ℕ) a ≤ t a
                intro a
                exact Nat.zero_le (t a)
              exact m.toSyn_monotone hzero_le_t
          have ht_eq_degree : t = m.degree f := by
            simpa [hfdeg0] using ht_eq_zero
          exact htop ht_eq_degree
        exact ⟨hdeg_eq, hg_ne, hcoeff_eq⟩
      rcases hnonTop with ⟨hdeg_eq, hg_ne, hcoeff_eq⟩
      rcases ih g hfg_step hg_ne hgI with
        ⟨q, hqG, hq_ne, u, hu_deg, d, hd_coeff⟩
      refine ⟨q, hqG, hq_ne, u, ?_, d, ?_⟩
      · simpa [hdeg_eq] using hu_deg
      · calc
          d * m.leadingCoeff q
              = g.coeff (m.degree g) := hd_coeff
          _ = g.coeff (m.degree f) := by rw [hdeg_eq]
          _ = f.coeff (m.degree f) := hcoeff_eq
  unfold MonomialOrder.IsGroebner
  apply le_antisymm
  · -- `span LT(⟨G⟩) ≤ span LT(G)`
    refine Ideal.span_le.mpr ?_
    intro q hq
    rcases hq with ⟨f, hfI, rfl⟩
    by_cases hf0 : f = 0
    · subst f
      simp
    · rcases htop_all f hf0 hfI with ⟨p, hpG, hp_ne, s, hs, c, hc⟩
      have hpLT :
          m.leadingTerm p ∈ Ideal.span (m.leadingTerm '' G) :=
        Ideal.subset_span ⟨p, hpG, rfl⟩
      have hmul :
          monomial s c * m.leadingTerm p ∈
            Ideal.span (m.leadingTerm '' G) :=
        Ideal.mul_mem_left _ _ hpLT
      have hEqLT :
          monomial s c * m.leadingTerm p = m.leadingTerm f := by
        calc
          monomial s c * m.leadingTerm p
              =
            monomial (s + m.degree p)
              (c * m.leadingCoeff p) := by
                simp [MonomialOrder.leadingTerm, monomial_mul]
          _ = monomial (m.degree f) (f.coeff (m.degree f)) := by
                rw [hs, hc]
          _ = m.leadingTerm f := by
                simp [MonomialOrder.leadingTerm,
                  MonomialOrder.leadingCoeff]
      simpa [hEqLT] using hmul
  · -- `span LT(G) ≤ span LT(⟨G⟩)`
    refine Ideal.span_le.mpr ?_
    intro q hq
    rcases hq with ⟨g, hgG, rfl⟩
    exact Ideal.subset_span
      ⟨g, Ideal.subset_span hgG, rfl⟩

/-- Gröbner basis definition implies item (x). -/
theorem isGroebner_imp_unique_normalForm_representatives
    (G : Set (MvPolynomial σ R))
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0) :
    m.IsGroebner G →
      ∀ f : MvPolynomial σ R,
        ∃! n : MvPolynomial σ R,
          Relation.IsNormalForm (m.ReducesToSet G) n ∧
            f - n ∈ Ideal.span G := by
  intro hGB f
  -- Existence of a normal form follows from well-foundedness of reduction.
  rcases
    Relation.exists_normalFormOf_of_wellFounded_flip
      (ReducesToSet.wellFounded m G) f
    with ⟨n, hfn, hn_nf⟩
  refine ⟨n, ?_, ?_⟩
  · -- `n` is a normal-form representative of the coset of `f`.
    constructor
    · exact hn_nf
    · exact m.sub_mem_span_of_reflTransGen G hfn
  · -- uniqueness
    intro n' hn'
    rcases hn' with ⟨hn'_nf, hfn'_span⟩
    have hfn_span : f - n ∈ Ideal.span G :=
      m.sub_mem_span_of_reflTransGen G hfn
    have hdiff_span : n - n' ∈ Ideal.span G := by
      have htmp : (f - n') - (f - n) ∈ Ideal.span G :=
        Ideal.sub_mem (Ideal.span G) hfn'_span hfn_span
      have hEq : (f - n') - (f - n) = n - n' := by
        ring
      simpa [hEq] using htmp
    -- Now prove `n' = n`.
    -- If `n - n' ≠ 0`, the Gröbner basis condition implies that
    -- `n - n'` is reducible modulo `G`.
    -- Since the leading term of `n - n'` comes from either `n` or `n'`,
    -- this contradicts that both `n` and `n'` are normal forms.
    by_cases hnn : n' = n
    · exact hnn
    · exfalso
      have hdiff_ne : n - n' ≠ 0 := by
        intro hzero
        apply hnn
        exact (sub_eq_zero.mp hzero).symm
      have hLT_mem_left :
          m.leadingTerm (n - n') ∈
            Ideal.span
              (m.leadingTerm ''
                (((Ideal.span G : Ideal (MvPolynomial σ R))))) := by
        exact Ideal.subset_span ⟨n - n', hdiff_span, rfl⟩
      have hLT_mem_G :
          m.leadingTerm (n - n') ∈ Ideal.span (m.leadingTerm '' G) := by
        rw [← hGB]
        exact hLT_mem_left
      have htop_div :
          ∃ p ∈ G, p ≠ 0 ∧
            ∃ s : σ →₀ ℕ, s + m.degree p = m.degree (n - n') := by
        classical
        -- Rewrite the leading-term ideal as the monomial ideal generated by
        -- the monic leading monomials of nonzero elements of `G`.
        have hLT_mem_monic :
            m.leadingTerm (n - n') ∈
              Ideal.span
                ((fun p : MvPolynomial σ R =>
                    MvPolynomial.monomial (m.degree p) (1 : R)) ''
                  (G \ {0})) := by
          simpa [MonomialOrder.span_leadingTerm_eq_span_monomial₀
            (m := m) (B := G) hG₀] using hLT_mem_G
        -- Re-index the generating set by exponent vectors.
        have hLT_mem_exp :
            m.leadingTerm (n - n') ∈
              Ideal.span
                ((fun a : σ →₀ ℕ =>
                    MvPolynomial.monomial a (1 : R)) ''
                  (m.degree '' (G \ {0}))) := by
          simpa [Set.image_image, Function.comp_def] using hLT_mem_monic
        -- Apply the monomial ideal membership criterion.
        have hmem :=
          (MvPolynomial.mem_ideal_span_monomial_image
            (x := m.leadingTerm (n - n'))
            (s := m.degree '' (G \ {0}))).1 hLT_mem_exp
        have hdeg_in_support :
            m.degree (n - n') ∈ (m.leadingTerm (n - n')).support := by
          rw [MonomialOrder.support_leadingTerm' (m := m) hdiff_ne]
          simp
        rcases hmem (m.degree (n - n')) hdeg_in_support with
          ⟨a, ha, hale⟩
        rcases ha with ⟨p, hpG0, hpa⟩
        rcases hpG0 with ⟨hpG, hp_not_zero_set⟩
        have hp_ne : p ≠ 0 := by
          simpa [Set.mem_singleton_iff] using hp_not_zero_set
        subst a
        -- Convert coordinatewise divisibility `m.degree p ≤ m.degree (n - n')`
        -- into additive divisibility.
        rcases le_iff_exists_add.mp hale with ⟨s, hs⟩
        refine ⟨p, hpG, hp_ne, s, ?_⟩
        -- Depending on the orientation of `le_iff_exists_add`, one of the
        -- following two lines should work.
        · simpa [add_comm] using hs.symm
      have hred_diff : m.ReducibleSet G (n - n') := by
        rcases htop_div with ⟨p, hpG, hp_ne, s, hs⟩
        have hp_unit : IsUnit (m.leadingCoeff p) := by
          rcases hG₀ p hpG with hunit | hp0
          · exact hunit
          · exact False.elim (hp_ne hp0)
        rcases hp_unit with ⟨u, hu⟩
        let c : R := ((u⁻¹ : Rˣ) : R) * (n - n').coeff (m.degree (n - n'))
        have hc : c * m.leadingCoeff p =
            (n - n').coeff (m.degree (n - n')) := by
          unfold c
          rw [← hu]
          calc
            (((u⁻¹ : Rˣ) : R) * (n - n').coeff (m.degree (n - n')) * (u : R))
                =
              (((u⁻¹ : Rˣ) : R) * (u : R)) *
                (n - n').coeff (m.degree (n - n')) := by
                  ring
            _ = (n - n').coeff (m.degree (n - n')) := by
                  simp
        refine
          ⟨(n - n') - monomial s c * p, ?_⟩
        refine ⟨p, hpG, m.degree (n - n'), hp_ne, ?_, s, hs, c, hc, rfl⟩
        exact MonomialOrder.degree_mem_support hdiff_ne
      rcases hred_diff with ⟨r, hstep⟩
      rcases hstep with ⟨p, hpG, t, hp_ne, ht, s, hs, c, hc, hr⟩
      have ht_or : t ∈ n.support ∨ t ∈ n'.support := by
        by_contra hnot
        have ht_not_n : t ∉ n.support := by
          intro ht_n
          exact hnot (Or.inl ht_n)
        have ht_not_n' : t ∉ n'.support := by
          intro ht_n'
          exact hnot (Or.inr ht_n')
        have hn_coeff : n.coeff t = 0 := by
          by_contra hc
          exact ht_not_n ((MvPolynomial.mem_support_iff).2 hc)
        have hn'_coeff : n'.coeff t = 0 := by
          by_contra hc
          exact ht_not_n' ((MvPolynomial.mem_support_iff).2 hc)
        have hdiff_coeff : (n - n').coeff t = 0 := by
          simp [coeff_sub, hn_coeff, hn'_coeff]
        exact (MvPolynomial.mem_support_iff.mp ht) hdiff_coeff
      have hp_unit : IsUnit (m.leadingCoeff p) := by
        rcases hG₀ p hpG with hunit | hp0
        · exact hunit
        · exact False.elim (hp_ne hp0)
      rcases hp_unit with ⟨u, hu⟩
      let cn : R := ((u⁻¹ : Rˣ) : R) * n.coeff t
      let cn' : R := ((u⁻¹ : Rˣ) : R) * n'.coeff t
      have unit_inv_mul_lc (a : R) :
          (((u⁻¹ : Rˣ) : R) * a) * m.leadingCoeff p = a := by
        rw [← hu]
        calc
          (((u⁻¹ : Rˣ) : R) * a) * (u : R)
              = (((u⁻¹ : Rˣ) : R) * (u : R)) * a := by
                  ring
          _ = a := by
                  simp
      rcases ht_or with ht_n | ht_n'
      · have hcn : cn * m.leadingCoeff p = n.coeff t := by
          unfold cn
          exact unit_inv_mul_lc (n.coeff t)
        have hn_red :
            m.ReducesToSet G n
              (n - monomial s cn * p) := by
          exact ⟨p, hpG, t, hp_ne, ht_n, s, hs, cn, hcn, rfl⟩
        exact hn_nf _ hn_red
      · have hcn' : cn' * m.leadingCoeff p = n'.coeff t := by
          unfold cn'
          exact unit_inv_mul_lc (n'.coeff t)
        have hn'_red :
            m.ReducesToSet G n'
              (n' - monomial s cn' * p) := by
          exact ⟨p, hpG, t, hp_ne, ht_n', s, hs, cn', hcn', rfl⟩
        exact hn'_nf _ hn'_red


/-- item (x) implies item (iv). -/
theorem unique_normalForm_representatives_imp_churchRosser
    (G : Set (MvPolynomial σ R)) :
    (∀ f : MvPolynomial σ R,
      ∃! n : MvPolynomial σ R,
        Relation.IsNormalForm (m.ReducesToSet G) n ∧
          f - n ∈ Ideal.span G) →
      Relation.ChurchRosser (m.ReducesToSet G) := by
  intro hrepr f g hfg
  rcases
    Relation.exists_normalFormOf_of_wellFounded_flip
      (ReducesToSet.wellFounded m G) f
    with ⟨nf, hfnf, hnf_nf⟩
  rcases
    Relation.exists_normalFormOf_of_wellFounded_flip
      (ReducesToSet.wellFounded m G) g
    with ⟨ng, hgng, hng_nf⟩
  have hf_nf_span : f - nf ∈ Ideal.span G := by
    exact m.sub_mem_span_of_eqvGen G hfnf.to_eqvGen
  have hf_ng_span : f - ng ∈ Ideal.span G := by
    apply m.sub_mem_span_of_eqvGen G
    exact Relation.EqvGen.trans _ _ _
      hfg
      hgng.to_eqvGen
  rcases hrepr f with ⟨n, hn, huniq⟩
  have hnf_eq : nf = n :=
    huniq nf ⟨hnf_nf, hf_nf_span⟩
  have hng_eq : ng = n :=
    huniq ng ⟨hng_nf, hf_ng_span⟩
  have hng_nf_eq : ng = nf :=
    hng_eq.trans hnf_eq.symm
  exact ⟨nf, hfnf, by simpa [hng_nf_eq] using hgng⟩


/--
Theorem 5.35: `IsGroebner` iff item (v).

A set `G` satisfies the Gröbner criterion iff every element of `⟨G⟩`
reduces to zero modulo `G`.
-/
theorem iff_idealElements_reduceTo_zero
    (G : Set (MvPolynomial σ R))
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0) :
    m.IsGroebner G ↔
      ∀ f : MvPolynomial σ R,
        f ∈ Ideal.span G →
          f ⟶*[m, G] 0 := by
  constructor
  · intro hGB
    have hx :
        ∀ f : MvPolynomial σ R,
          ∃! n : MvPolynomial σ R,
            Relation.IsNormalForm (m.ReducesToSet G) n ∧
              f - n ∈ Ideal.span G := by
              intro f
              exact isGroebner_imp_unique_normalForm_representatives m G hG₀ hGB f
    have hcr : Relation.ChurchRosser (m.ReducesToSet G) :=
      unique_normalForm_representatives_imp_churchRosser m G hx
    exact (churchRosser_iff_idealElements_reduceTo_zero m G hG₀).1 hcr
  · intro hred
    have hnonzero_red :
        ∀ f : MvPolynomial σ R,
          f ≠ 0 →
          f ∈ Ideal.span G →
            m.ReducibleSet G f :=
      idealElements_reduceTo_zero_imp_nonzero_idealElements_reducible m G hred
    exact nonzero_idealElements_reducible_imp_isGroebner m G hnonzero_red

/--
Theorem 5.35: `IsGroebner` iff item (vi).
-/
theorem iff_nonzero_idealElements_reducible
    (G : Set (MvPolynomial σ R))
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0) :
    m.IsGroebner G ↔
      ∀ f : MvPolynomial σ R,
        f ≠ 0 →
        f ∈ Ideal.span G →
          m.ReducibleSet G f := by
  constructor
  · intro hGB
    exact idealElements_reduceTo_zero_imp_nonzero_idealElements_reducible m G
      ((iff_idealElements_reduceTo_zero m G hG₀).1 hGB)
  · intro hred
    exact nonzero_idealElements_reducible_imp_isGroebner m G hred

/--
Theorem 5.35: `IsGroebner` iff item (iv).

The Gröbner criterion is equivalent to the Church--Rosser property.
-/
theorem iff_churchRosser
    (G : Set (MvPolynomial σ R))
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0) :
    m.IsGroebner G ↔
      Relation.ChurchRosser (m.ReducesToSet G) := by
  exact
    (iff_idealElements_reduceTo_zero m G hG₀).trans
      (churchRosser_iff_idealElements_reduceTo_zero m G hG₀).symm

/--
Theorem 5.35: `IsGroebner` iff item (i).

The Gröbner criterion is equivalent to local confluence of reduction
modulo `G`.
-/
theorem iff_locallyConfluent
    (G : Set (MvPolynomial σ R))
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0) :
    m.IsGroebner G ↔
      Relation.LocallyConfluent (m.ReducesToSet G) := by
  have hgb_cr :
      m.IsGroebner G ↔
        Relation.ChurchRosser (m.ReducesToSet G) :=
    iff_churchRosser (m := m) G hG₀
  constructor
  · intro hgb
    exact Relation.ChurchRosser.locallyConfluent (hgb_cr.1 hgb)
  · intro hlc
    apply hgb_cr.2
    exact Relation.Confluent.churchRosser
      (Relation.confluent_of_wellFounded_flip_of_locallyConfluent
        (ReducesToSet.wellFounded m G)
        hlc)

/--
Theorem 5.35: `IsGroebner` iff item (ii).

The Gröbner criterion is equivalent to confluence of reduction modulo `G`.
-/
theorem iff_confluent
    (G : Set (MvPolynomial σ R))
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0) :
    m.IsGroebner G ↔
      Relation.Confluent (m.ReducesToSet G) := by
  have hgb_cr :
      m.IsGroebner G ↔
        Relation.ChurchRosser (m.ReducesToSet G) :=
    iff_churchRosser (m := m) G hG₀
  constructor
  · intro hgb
    exact Relation.confluent_of_wellFounded_flip_of_locallyConfluent
      (ReducesToSet.wellFounded m G)
      (Relation.ChurchRosser.locallyConfluent (hgb_cr.1 hgb))
  · intro hconf
    apply hgb_cr.2
    exact Relation.Confluent.churchRosser hconf

/--
Theorem 5.35: `IsGroebner` iff item (iii).

The Gröbner criterion is equivalent to uniqueness of normal forms.
-/
theorem iff_uniqueNormalForms
    (G : Set (MvPolynomial σ R))
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0) :
    m.IsGroebner G ↔
      Relation.UniqueNormalForms (m.ReducesToSet G) := by
  have hgb_conf :
      m.IsGroebner G ↔
        Relation.Confluent (m.ReducesToSet G) :=
    iff_confluent (m := m) G hG₀
  constructor
  · intro hgb
    exact Relation.uniqueNormalForms_of_confluent
      (hgb_conf.1 hgb)
  · intro hunf
    apply hgb_conf.2
    exact Relation.confluent_of_wellFounded_flip_of_uniqueNormalForms
      (ReducesToSet.wellFounded m G)
      hunf

/--
Theorem 5.35: `IsGroebner` iff item (x).

The Gröbner criterion is equivalent to uniqueness of normal-form
representatives modulo `⟨G⟩`.
-/
theorem iff_unique_normalForm_representatives
    (G : Set (MvPolynomial σ R))
    (hG₀ : ∀ g ∈ G, IsUnit (m.leadingCoeff g) ∨ g = 0) :
    m.IsGroebner G ↔
      ∀ f : MvPolynomial σ R,
        ∃! n : MvPolynomial σ R,
          Relation.IsNormalForm (m.ReducesToSet G) n ∧
            f - n ∈ Ideal.span G := by
  constructor
  · exact isGroebner_imp_unique_normalForm_representatives m G hG₀
  · intro hx
    -- x → iv
    have hcr : Relation.ChurchRosser (m.ReducesToSet G) :=
      unique_normalForm_representatives_imp_churchRosser m G hx
    -- iv → v
    have hred :
        ∀ f : MvPolynomial σ R,
          f ∈ Ideal.span G →
            f ⟶*[m, G] 0 :=
      (churchRosser_iff_idealElements_reduceTo_zero m G hG₀).1 hcr
    -- v → vi
    have hnonzero_red :
        ∀ f : MvPolynomial σ R,
          f ≠ 0 →
          f ∈ Ideal.span G →
            m.ReducibleSet G f :=
      idealElements_reduceTo_zero_imp_nonzero_idealElements_reducible m G hred
    -- vi → Gröbner basis definition
    exact nonzero_idealElements_reducible_imp_isGroebner m G hnonzero_red

end CommRing

end IsGroebner

end MonomialOrder
